version: '3.4'

services:

  petprojectdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: petprojectdb
    hostname: petprojectdb
    restart: always
    ports:
    - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Sa@123456"

  materdatacache:
    image: redis
    container_name: materdatacache
    restart: always
    ports:
    - 6379:6379

  masterdataapi:
    image: masterdataapi
    container_name: masterdata  
    restart: always  
    build:
      context: .
      dockerfile: Services/MasterData/MasterData.API/Dockerfile
    ports:
      - "5000:5000"
