version: '3.4'

networks:
  PetProject:

services:
  petprojectdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: petprojectdb
    hostname: petprojectdb
    restart: always
    ports:
    - "1433:1433"
    networks: 
    - PetProject
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Sa@123456"

  materdatacache:
    image: redis
    container_name: materdatacache
    restart: always
    ports:
    - 6379:6379
    networks: 
    - PetProject

  identityapi:
    image: identityapi
    container_name: identityapi  
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    ports:
      - "6000:6000"    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=6000
      - PET_PROJECT_JWT_SECURITY_KEY=rWRSlbDofIojJkwAN1tip36aK4FO0DLx
      - PET_PROJECT_JWT_TOKEN_VALIDITY_MINS=180
    networks: 
    - PetProject
    depends_on:
      - petprojectdb
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  masterdataapi:
    image: masterdataapi
    container_name: masterdataapi
    build:
      context: .
      dockerfile: Services/MasterData/MasterData.API/Dockerfile
    ports:
      - "5000:5000"    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - PET_PROJECT_JWT_SECURITY_KEY=rWRSlbDofIojJkwAN1tip36aK4FO0DLx
      - PET_PROJECT_JWT_TOKEN_VALIDITY_MINS=180
    depends_on:
      - petprojectdb
      - materdatacache
    networks: 
    - PetProject
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  petprojectgateway:
    image: petprojectgateway
    container_name: petprojectgateway  
    build:
      context: .
      dockerfile: PetProject.APIGateway/Dockerfile
    ports:
      - "9000:9000"    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=9000
    networks: 
    - PetProject
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
