services:
  IdentityDb:
    container_name: IdentityDb
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'

  PetProjectDb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: petprojectdb
    hostname: petprojectdb
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Sa@123456"

  # IdentityService:
  #   container_name: IdentityApi
  #   image: identity
  #   build:
  #     context: .
  #     dockerfile: ./Identity/Dockerfile
  #   ports:
  #     - '9000:9000'
  #   depends_on:
  #     - IdentityDb

